version: "3"
services:
  # Setup custom Jenkins with docker-compose
  jenkins:
    container_name: smartcine-jenkins
    build:
      context: . # use the current directory as the build contexts
      dockerfile: Dockerfile
    ports:
      - 9996:8080
      - 50000:50000
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
